### ISSUE TITLE
Oculus Quest Controllers

### ISSUE THREAD

**Issue by visjack** [balataca/unity3d-oculus-pointer#1]
Hi there, saw your comment on Andrew's video and downloaded your git and have been using it to develop an app for Go very well. I am now looking at porting to the Quest but wanting to keep the same app which could be used for the Quest or the Go. I'm trying to figure out how to integrate quest controllers in the same way but can't get my head around it. I've got it so that the quest controller back button works to exit the app but can't get the pointer working. I've also had some issues with the fallback if there is no pointer to use a raycast (although I've not spent any time reviewing this).

**Comment by visjack** [comment]
I've managed to crack it by using the OVRControllerPrefab within the hand anchors and hiding the 3d model within the pointer prefab. Would be good to know if there is a better / smoother way to do it

**Comment by balataca** [comment]
I think it would be better if in the Pointer component we added a setting (variable) to select the 3d model controller with these options (Oculus Go, Quest, Gear VR). If you want please consider making a pull request with your changes, so we could integrate these to the project. What do you think about it?
