### ISSUE TITLE
Laser Pointer Stop working after Load.Scene

### ISSUE THREAD

**Issue by Seginus1** [balataca/unity3d-oculus-pointer#2]
Hey! I've been struggling with laser pointer and LoadScene lately. The pointer works fine at everything that I wanted to do in project, but when I'm trying to change scene in build mode, laser pointer stops working.  Do you have any idea why is this happening?
To load the new scene I use an object as interactable with the pointer script and then in C# I have this code:

public void MyScene()
{
    SceneManager.LoadScene(1);
}

The load scene is working fine and the scene changes, only the pointer stop working.
I'm using Oculus Go.

**Comment by balataca** [comment]
Hello, thanks for sending an issue.

Maybe when you are changing the scene, the Pointer object is getting destroyed and is not initialized again. Also, is there any error messages in the console?

I would also check if the EventSystem and other components are present in the other scenes.

I also recommend that you check out the native [XR Toolkit](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@0.9/manual/index.html) implementation on unity. It's a powerfull native solution to VR interactions and really easy to implement.
